#!/usr/bin/env bash
USAGE="$0: [-h --help ] [ -r --remove ] [-d --dir ] FILE COMMENT"
remove=0
args(){
    case $1 in 
        -h|--help) echo $USAGE
            exit 0
            ;;
        -r|--remove) remove=1
            shift
            args $@
            ;;
        -d|--dir) cd ~/$2
            shift 2
            args $@
            ;;
esac

if [[ $remove == 0 ]]; then
    git add $1
else
    git rm $1
fi

git commit -m "$2"
git push origin master
exit 0
}
args $@
