#!/usr/bin/env bash
#
# Written by: crossroads1112
# Purpose: Prints LAN IP and WAN IP
#
############################3
echo "Internal IP address:"
ip route get 8.8.8.8 | awk -F'src ' '!/cache/{print $2}'
echo ""
echo "External IP address:"
curl icanhazip.com
