#!/usr/bin/env bash
#
# Written by: Chad Sharp
#
# Purpose: Ease the process of uploading packages to the AUR
#
#########################
helpmsg="${0##*/} [OPTIONS] FILES\n\n-h\t\tPrint this help message\n-u\t\tDon't upload the package to AUR\n-n\t\tDon't try building package before creating the src.tar.gz"
tmpdir=/tmp/mkaur
nobuild=0
noupload=0
if (( $# == 0 )); then
    echo "ERROR: No arguments. Please specify the files you want to add to the AUR package (e.g. the PKGBUILD, .install script etc.)"
    echo -e "\n$helpmsg"
    exit 1
fi
while getopts "hnb" OPT; do
    case $OPT in
        h) echo -e $helpmsg; exit 0 ;;
        u) noupload=1; shift;;
        b) nobuild=1; shift;;
        *) echo "Unrecognized argument"; exit 1 ;;
    esac
done
if (( $# == 0 )); then
    echo "This script requires arguments (the files you want to package)"
    exit 1
fi

if [[ -d "$tmpdir" ]]; then 
    rm -rf "$tmpdir"
fi

mkdir "$tmpdir"
cp "$@" "$tmpdir"
cd "$tmpdir"
if [[ $nobuild == 0 ]] ; then
    makepkg -d || { echo "Build failed. Aborting"; exit 1; }
fi
mkdir -p "$tmpdir/aurpkg"

for i in "${@##*/}"; do 
    mv "${tmpdir}/${i}" "${tmpdir}/aurpkg/${i}"
done
cd "${tmpdir}/aurpkg"
mkaurball

if [[ ! $noupload == 1 ]]; then
    if which aurploader > /dev/null; then
        aurploader -k -a -l ~/.config/aurploader
    else
        xdg-open https://aur.archlinux.org/submit/
    fi
else 
    echo "Package located in $tmpdir/aurpkg"
fi
