#!/usr/bin/env bash
#
# Written by: Chad Sharp
#
# Purpose: Ease the process of uploading packages to the AUR
#
#########################
helpmsg="${0##*/} [OPTIONS] FILES\n\n-h\t\tPrint this help message\n-u\t\tUpload the package to AUR\n-n\t\tDon't try building package before upload"
tmpdir=/tmp/scratch
nobuild=0
while getopts "hnb" OPT; do
    case $OPT in
        h) echo -e $helpmsg; exit 0 ;;
        n) noupload=1;;
        b) nobuild=1;;
        *) echo "Unrecognized argument"; exit 1 ;;
    esac
done
[[ $noupload == 1 ]] && shift
[[ $nobuild == 1 ]] && shift
if (( $# == 0 )); then
    echo "This script requires arguments (the files you want to package)"
    exit 1
fi

if [[ -d $tmpdir ]]; then 
    rm -rf $tmpdir
fi

mkdir $tmpdir
cp $@ $tmpdir
cd $tmpdir
if [[ $nobuild == 0 ]] ; then
    makepkg -d || { echo "Build failed. Aborting"; exit 1; }
fi
mkdir -p $tmpdir/aurpkg

for i in ${@##*/}; do 
    mv ${tmpdir}/${i} ${tmpdir}/aurpkg/${i}
done
cd ${tmpdir}/aurpkg
mkaurball

if [[ ! $noupload == 1 ]]; then
    if which aurploader > /dev/null; then
        aurploader -k -a -l ~/.config/aurploader
    else
        xdg-open https://aur.archlinux.org/submit/
    fi
else 
    echo "Package located in $tmpdir/aurpkg"
fi
