#!/bin/bash
dotfilesdir=~/.dotfiles
gsend(){
    git add $1
    git commit -vm "$2"
    git push origin master
}
pacman -Qqn > /home/chad/.dotfiles/pacman_pkgs
pacman -Qqm > /home/chad/.dotfiles/aur_pkgs

cd $dotfilesdir
gsend pacman_pkgs "cron push"
gsend aur_pkgs "cron push"
