#!/usr/bin/env bash
bold=$(tput bold)
normal=$(tput sgr0)
[[ $# == 0 ]] && echo "${0##*/}: This script requires at least one argument"
while [[ $# > 0 ]]; do
remmsg="${bold}$1${normal} removed"

    if [[ -f $1 || -h $1 ]]; then
        rm $1 && echo "File $remmsg"
        shift
    elif [[ -d $1 ]]; then
        if [[ -z $(ls -A $1 ) ]]; then
            rmdir $1 && echo "Empty directory $remmsg"
            shift
        else
            echo -n "$1 is a directory. Do you still want to delete it? [Y/n] "
            read del
            case $del in
                ""|[Yy]|[Yy][Ee][Ss]) rm -rf $1 && echo "Directory $remmsg recursively" ;;
            esac
            shift
        fi
    elif [[ ! -e $1 ]]; then
        echo "$1 does not exist"
        shift
    else
        echo "$1 is not a regular file or directory. You'll have to use rm itself."
        shift
    fi
done
