#!/usr/bin/env bash
bold=$(tput bold)
normal=$(tput sgr0)
while [[ $@ != "" ]]; do
remmsg="${bold}$1${normal} removed"

    if [[ -f $1 || -h $1 ]]; then
        rm $1 && echo "$remmsg"
        shift
    elif [[ -d $1 ]]; then
        echo -n "$1 is a directory. Do you still want to delete it? [Y/n] "
        read del
        case $del in
            ""|[Yy]|[Yy][Ee][Ss]) rm -rf $1 && echo "$remmsg" ;;
        esac
        shift
    elif [[ ! -e $1 ]]; then
        echo "$1 does not exist"
        shift
    else
        echo "$1 is not a regular file or directory. You'll have to use rm itself."
        shift
    fi
done
