#! /usr/bin/env bash
log_path="/var/local/log/rollback"
date=$(date "+%Y-%m-%d-%H%M%S")
log_file="${log_path}/rollback_${date}.log"

if (( EUID != 0 )); then
    echo "This script must be run as root" 1>&2
    exit 1
fi

if [ !  -d "$log_path" ]; then
    mkdir $log_path
fi

exec > >(tee -a "$log_file")
exec 2> >(tee -a "$log_file" >&2)

clear
echo 'Do you want to rollback a [d]aily snapshot or an [u]pgrade?' 
read input

if  [[ $input == "u" ]]; then
    clear
    echo 'Undoing most recent upgrade'
    pre=$(sudo snapper list --type pre-post | tail -n -1 | awk -F\| '{print $1}' | tr -d ' ')
    snapper -v undochange $pre..$((pre+1))

elif [[ $input == "d" ]]; then
    clear
    snapper list --type single | awk -F\| '{print $1"|" $2}'| sed '1,3d' 
    echo -e "\n What is the number of the snapshot you like to return to?"
    read past
    snapper undochange $past..0
    
else
    echo "$input is not an acceptable response"
    
fi
