#!/usr/bin/env bash
#
#
# Written by: erikw
# Modified by: crossroads1112
# Purpose: Runs a command wrapped in pre-post snapshots. Snapper supports ext4, btrfs and LVM.
#
###############################################
 
cmd="$@" #Set all arguments to $cmd
 
snapshot_nbr=$(snapper create --type=pre --cleanup-algorithm=number --print-number --description="${cmd}") #Create snapshot and grab number
echo -e "> New pre snapshot with number ${snapshot_nbr}."
echo -e "> Running command \"${cmd}\"."
 
eval "$cmd" #Run arguments
 
snapshot_nbr=$(snapper create --type=post --cleanup-algorithm=number --print-number --pre-number="$snapshot_nbr") #Create post snapshot and grab number
echo -e "\n> New post snapshot with number ${snapshot_nbr}."
