#!/usr/bin/env bash
# subdu AKA "subvolume du"
# Written by: crossroads1112
# Purpose: Get human readable output from btrfs qgroup show
#
##################################################
mount="/"
[[ -n $1 ]] && mount="$1"

sudo btrfs qgroup show $mount > /tmp/subdu
trap "[[ -f /tmp/subdu ]] && rm  /tmp/subdu" EXIT ERR 15 1 2
eval "$(sudo btrfs subvolume list $mount | sed 's/\//\\\//g' | awk '{print "sed -i -e \"s/[0-9][0-9]*\\/"$2 "/" $9"/\" "}' | sed -e 's/$/\/tmp\/subdu/')"
tr -s ' ' '\t'  </tmp/subdu  | sed -e "/^[0-9][0-9]*/d"  | sed 's/qgroupid/subvol/' | column -t 
