#!/usr/bin/env bash
# subdu AKA "subvolume du"
# Written by: crossroads1112
# Purpose: Get human readable output from btrfs qgroup show
#
##################################################
mount="/"
[[ -n $1 ]] && mount="$1"

sudo btrfs qgroup show $mount > /tmp/subdu
trap "[[ -f /tmp/subdu ]] && rm  /tmp/subdu" EXIT ERR 15 1 2
eval "$(sudo btrfs subvolume list / | sed 's/\//\\\//g' | awk '{print "sed -i -e \"s/"$2 "/"$2 " " $9"/\" "}'| sed -e 's/$/\/tmp\/subdu/')"
sed 's/qgroupid/subvol qgroupid/' /tmp/subdu | awk 'NF>3' | tr -s ' ' '\t'  | column -t   
