#!/usr/bin/env bash
#
# Written by: crossroads1112
#
# Purpose: Super simple script run in a systemd timer. My .zshrc tails /etc/updates.txt to tell me how many updates are available.
#
#
#############################################
pkgs="$(checkupdates; if type pacaur &>/dev/null; then pacaur -k --color never; else checkupdates;fi)"
updatenum=$(wc -l <<<"$pkgs")
case updatenum in 
    0) updates="no packages";;
    1) updates="1 package" ;;
    *) updates="$updatenum packages" ;;
esac

echo -e "As of $(date "+%D at %r"), you have $updates available to upgrade.\n$(sed 's/^/* /' <<< "$pkgs")"  > /etc/updates.txt
