#!/usr/bin/env bash
#
# Written by: crossroads1112
# Purpose: Very simple script that eases the process of using mpv instead of flash
# The only reason this isn't a function in my zshrc is because the argument counting was giving me fits
#
#####################
if [[ $# == 0 ]]; then
    video=$(xclip -o)
elif [[ $# == 1 ]]; then
    video=$1
else
    echo "Too many arguments. Aborting."
    exit 1
fi

mpv --ytdl $video
