.TH PACUPG 1
.SH NAME
pacupg \- wrap upgrades in btrfs snapshots with optional backups of /boot
.SH SYNOPSYS
.B pacupg
[\fB\-h\fR]
[\fB\-b\fR]
[\fB\-a\fR]
[\fB\-r\fR]
.SH DESCRIPTION
.B pacupg
wrap upgrades in btrfs snapshots with optional backups of /boot (happens automatically when kernel update detected)
.TP
The script logs every upgraded package (with version numbers) to /var/local/log/pacupg/
.SH OPTIONS
.TP
.BR \-h\fR
Display help message
.TP
.BR \-b\fR
Force boot backup even if /boot is not on a separate partition
.TP
.BR \-a\fR
Upgrade AUR packages as well (requires pacaur)
.TP
.BR \-r\fR
Rollback previous upgrades
